export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const SIGN_IN = "SIGN_IN";
export const POSTS = "POSTS";
export const RECEIVE_FACTORY_DATA = "RECEIVE_FACTORY_DATA"
export const ADD_FACTORY_DATA = "ADD_FACTORY_DATA"
export const UPDATE_FACTORY_DATA = "UPDATE_FACTORY_DATA"
